### ISSUE TITLE
Links in study room reservation email link to localhost URL

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/booked#3]
The email confirmation I received included links that link to http://localhost - it looks like perhaps a configuration may need to be adjusted.  Email is below:

Reservation Details:

Starting: 09/23/2016 @ 9:00 AM (America/New_York)
Ending: 09/23/2016 @ 11:00 AM (America/New_York)
Resource: Room 605-B
Title:
Description:

[View this reservation](http://localhost/Web/reservation.php?rn=57e526d31d6e0908578732) | [Add to Calendar](http://localhost/Web/export/ical.php?rn=57e526d31d6e0908578732) | [Log in to Booked Scheduler](http://localhost/Web)

**Comment by ihardy** [comment]
Fixed, Thanks for the heads up Dan
