### ISSUE TITLE
Delete & Update reservation buttons are not enabled for regular users 

### ISSUE THREAD

**Issue by kerchner** [gwu-libraries/booked#4]
When I view my reservation (e.g. https://rooms.library.gwu.edu/Web/reservation.php?rn=57e526d31d6e0908578732 ) I am only presented with `Close` and `Print` buttons.  When @cummingsm is logged in, he also has `Update` and `Delete` buttons.  Perhaps these are only enabled for users with elevated permissions.  However, this leaves regular users with no way to delete or update reservations.

**Comment by ihardy** [comment]
Enabled Delete for all users. This allows users to update by deleting/rescheduing if needed.
